<a href="https://colab.research.google.com/github/lcduquev/Analisis-Numerico/blob/master/Chapter%204/Convex_Programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cvxpy as cp
import numpy as np
import math

#4.5.1

In [ ]:
A = np.array([[1 ,- 10*math.log10(10)], 
     [1 ,- 10*math.log10(20)],
     [1 ,- 10*math.log10(50)],
     [1 ,- 10*math.log10(100)],
     [1 ,- 10*math.log10(300)]])


In [ ]:
b = np.array([-70,-75,-90,-110,-125])

In [ ]:
# Define and solve the CVXPY problem.
x = cp.Variable(2)
cost = cp.sum_squares(A @ x - b)
prob = cp.Problem(cp.Minimize(cost))
prob.solve()

# Print result.
print("\nThe optimal value is", cp.norm(A @ x - b, p=2).value)
print("The optimal x is")
print(x.value)


The optimal value is 7.524206953382565
The optimal x is
[-26.7439583    3.96691516]


#4.5.2

In [ ]:
W = 1
rth = np.array([2, 1])
a= np.array([1, 1])
b = np.array([1, 0.5])

p = cp.Variable(2)
w = cp.Variable(2)

prob = cp.Problem(cp.Minimize(sum(p)**2),
                 [
                  rth[0]*cp.log(2) + a[0]*cp.kl_div(w[0],w[0]+b[0]*p[0]) - a[0]*b[0]*p[0] <= 0,   
                  rth[1]*cp.log(2) + a[1]*cp.kl_div(w[1],w[1]+b[1]*p[1]) - a[1]*b[1]*p[1] <= 0,                           
                  w >=0,
                  p >=0,
                  sum(w)==W
                  ])
prob.solve()

print("\nThe optimal value is", prob.value)
print("A solution p is")
print(p.value)
print("A solution w is")
print(w.value)


The optimal value is 83.35315477842217
A solution p is
[5.15674609 3.9730488 ]
A solution w is
[0.62189165 0.37810835]
A dual solution corresponding to the inequality constraints is
169.6687706044418


#4.5.3

In [ ]:
m = 4;
SINR = np.array([ [15], [12], [9], [6] ]) 
noise_pow = 1e-9

H=np.zeros((m,m))

for i in range(m):
  for j in range(m):
    H[i,j] = np.exp(-abs(i-j))

d = np.diag(H)
p = cp.Variable((m,1))

prob = cp.Problem(cp.Minimize(sum(p)),
                  [SINR*(H-np.diag(d)).T@p  + SINR*noise_pow - d*p <= 0,
                   p >= 0
                  ])
prob.solve()
print("status:", prob.status)
print("\nThe optimal value is", prob.value)
print("A solution p is")
print(p.value)

status: optimal_inaccurate

The optimal value is 1.9983388098097472e-08
A solution p is
[[8.64501405e-09]
 [5.82952061e-10]
 [9.05976727e-11]
 [1.06648243e-08]]


#4.5.4

In [ ]:
d = np.array([[1],[2],[3]]) # demand
s = np.array([[3],[3],[3]]) # supply
n = 3;
b = np.ones((n,1));

x=cp.Variable((n,n))

prob = cp.Problem(cp.Minimize(sum(x[0,:])**2 + sum(x[1,:])**2),
                  [x.T@b == d,
                   x@b <= s,
                   x >= 0
                  ])
prob.solve()

print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)



The optimal value is 4.5
A solution x is
[[0.16666667 0.5        0.83333333]
 [0.16666667 0.5        0.83333333]
 [0.66666667 1.         1.33333333]]
